apiVersion: v1
kind: ResourceQuota
metadata:
  name: test
spec:
  hard:
    pods: "10"
    services: "4"
    services.loadbalancers: "5"
    secrets: "8"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi 