apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  strategy: {}
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: nginx: 1.20.2
        name: nginx
        resources: {}
        volumeMounts:
         - name: config-vol
           mountPath: "/etc/config"
           readOnly: true
      volumes:
       - name: config-vol
         configMap:
          name: test