apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-deploy
  name: test-deploy
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-deploy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        volumeMounts:
         - name: vol
           mountPath: "/etc/cm"
           readOnly: true
      volumes:
       - name: vol
         configMap:
         name: test-cm

status: {}